apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: ml-training
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/da25g510/ml-data/data
    type: DirectoryOrCreate
